<?php

declare(strict_types=1);

namespace Tests\Unit\Schema\Definition;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\TestCase;

#[CoversClass(\ZtdQuery\Platform\Postgres\Schema\Definition\ColumnDefinition::class)]
#[\PHPUnit\Framework\Attributes\UsesClass(\ZtdQuery\Platform\Postgres\Schema\PgSqlColumnTypeMapper::class)]
#[\PHPUnit\Framework\Attributes\UsesClass(\ZtdQuery\Platform\Postgres\Sql\PgSqlLexerProfile::class)]
#[\PHPUnit\Framework\Attributes\UsesClass(\ZtdQuery\Platform\Postgres\Schema\Definition\ColumnTypeDeclaration::class)]
#[\PHPUnit\Framework\Attributes\UsesClass(\ZtdQuery\Platform\Postgres\Schema\Definition\TableConstraint::class)]
final class ColumnDefinitionTest extends TestCase
{
    public function testParseColumnDefinition(): void
    {
        self::assertEquals(['name' => 'id', 'type' => 'BIGINT', 'columnType' => new \ZtdQuery\Schema\ColumnDeclaration(family: \ZtdQuery\Schema\ColumnTypeFamily::INTEGER, nativeType: 'BIGINT'), 'notNull' => false, 'primaryKey' => true, 'unique' => false, 'default' => null, 'identity' => true, 'generatedExpression' => null], (new \ZtdQuery\Platform\Postgres\Schema\Definition\ColumnDefinition())->parseColumnDefinition('id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY'));
    }

    public function testIsSequenceDefault(): void
    {
        self::assertSame(true, \ZtdQuery\Platform\Postgres\Schema\Definition\ColumnDefinition::isSequenceDefault("nextval('users_id_seq'::regclass)"));
    }

    public function testIsSerialType(): void
    {
        self::assertSame(true, \ZtdQuery\Platform\Postgres\Schema\Definition\ColumnDefinition::isSerialType('BIGSERIAL'));
    }

    public function testHasGeneratedIdentity(): void
    {
        self::assertSame(true, \ZtdQuery\Platform\Postgres\Schema\Definition\ColumnDefinition::hasGeneratedIdentity('GENERATED BY DEFAULT AS IDENTITY NOT NULL'));
    }
    public function testGeneratedExpressionExcludesIdentityColumns(): void
    {
        $column = new \ZtdQuery\Platform\Postgres\Schema\Definition\ColumnDefinition();
        self::assertSame('(a + b)', $column->generatedExpression('GENERATED ALWAYS AS (a + b) STORED', false));
        self::assertNull($column->generatedExpression('GENERATED ALWAYS AS IDENTITY', true));
    }
}
